### PR TITLE
[DRAFT] RFC: Attributes galore

### PR DESCRIPTION
**Pull request by Centril**
[Rendered](https://github.com/Centril/rfcs/blob/rfc/attributes-galore/text/0000-attributes-galore.md)

This is a **draft** version of an RFC for you to review, before a formal proposal is made for consideration.

### CODE REVIEW

**Comment by Centril** [comment]
cc @petrochenkov @kennytm

**Comment by petrochenkov** [comment]
LGTM, generally, didn't look into the details too much.

Precedence in types needs to be figured out.
Attributes on expressions are not allowed in all positions right now, also due to precedence issues (I never investigated the details though).
Type grammar is somewhat similar to expression grammar, so similar issues may exist as well.

**Comment by Centril** [comment]
@petrochenkov Cool; I based the changes around [type.g](https://github.com/rust-lang-nursery/wg-grammar/blob/6ad653f47e147e5b1827369417a63ed31e2d5bcf/grammar/type.g); I couldn't think of any notable ambiguities but we might find some during implementation perhaps. The only one that stuck out was `where #[foo] A: B` where the RFC proposes an interpretation `where #[foo] (A: B)` as opposed to `where (#[foo] A): B`.

**Comment by petrochenkov** [comment]
Yeah, that mirrors the `for<'a> A: B` ambiguity as well where `for<'a>` is interpreted as applied to the whole predicate rather than as a part of the type `for<'a> A`.

**Comment by Centril** [comment]
Filed as https://github.com/rust-lang/rfcs/pull/2602. :)

**Pull request closed without merging**
